cleanupUnusedCatalogs: true

shellEmulator: true

packages:
  - packages/*
  - playground

overrides:
  '@v-c/resize-observer': catalog:vc
  '@v-c/util': catalog:vc

catalog:
  '@vitest/coverage-v8': ^4.1.9
  '@vitest/ui': 4.1.9

catalogs:
  dev:
    '@antfu/eslint-config': ^7.7.3
    '@testing-library/jest-dom': ^6.9.1
    '@vitejs/plugin-vue': ^6.0.7
    '@vitejs/plugin-vue-jsx': ^5.1.6
    '@vue/test-utils': ^2.4.11
    '@vue/tsconfig': ^0.8.1
    bumpp: ^10.4.1
    cross-env: ^10.1.0
    eslint: ^9.39.4
    eslint-plugin-format: ^2.0.1
    jsdom: ^27.4.0
    lint-staged: ^16.4.0
    mockdate: ^3.0.5
    npm-run-all: ^4.1.5
    pretty-format: ^30.4.1
    simple-git-hooks: ^2.13.1
    tsdown: 0.22.3
    tsx: ^4.22.4
    turbo: ^2.10.0
    typescript: ~5.9.3
    vite: ^8.1.0
    vite-plugin-tsx-resolve-types: ^1.0.1
    vitest: ^4.1.9
    vue-tsc: ^3.3.5
  prod:
    '@antdv-next/cssinjs': ^1.0.6
    '@antdv-next/icons': ^1.0.8
    antdv-next: ^1.3.7
    dayjs: ^1.11.21
    vue: ^3.5.38
  types:
    '@types/node': ^25.9.4
  vc:
    '@v-c/resize-observer': ^1.1.2
    '@v-c/util': ^1.0.19

onlyBuiltDependencies:
  - esbuild
