<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { useLocale } from '@/composables/use-locale'

interface ContributorsData {
  logins: string[]
  components: Record<string, number[]>
  blog: Record<string, number[]>
  'docs/vue': Record<string, number[]>
}

interface ResultData {
  login: string
  url: string
  avatar: string
}

defineOptions({ name: 'Contributors' })

const { t } = useLocale()
const route = useRoute()

// contributors.json is generated by `pnpm contributors`
// (scripts/generate-contributors.ts) from the antdv-next-pro repo.
const files = import.meta.glob('@/assets/contributors.json', { eager: true, query: '?raw', import: 'default' })

function resolveDocKey(parts: string[]): { module: keyof ContributorsData, key: string } | null {
  // /components/<name> -> module components, key <name>
  if (parts[0] === 'components') {
    return { module: 'components', key: parts[1] ?? '' }
  }
  // /docs/vue/<page> -> module docs/vue, key <page>
  if (parts[0] === 'docs' && parts.length >= 3) {
    return { module: 'docs/vue', key: parts[parts.length - 1] }
  }
  return null
}

const contributors = computed<ResultData[]>(() => {
  const raw = Object.values(files)[0]
  if (!raw) {
    return []
  }
  let data: ContributorsData
  try {
    data = JSON.parse(String(raw))
  }
  catch {
    return []
  }

  const parts = route.path.split('/').filter(Boolean).map(part => part.replace(/-cn$/, ''))
  const doc = resolveDocKey(parts)
  if (!doc) {
    return []
  }

  const indexes = data[doc.module]?.[doc.key] ?? []
  return indexes.map((index) => {
    const login = data.logins[index]
    return {
      login,
      url: `https://github.com/${login}`,
      avatar: `https://github.com/${login}.png?size=80`,
    }
  })
})
</script>

<template>
  <div v-if="contributors.length > 0" class="contributors-container">
    <div class="title">
      {{ t('layout.contributors.title') }}
    </div>
    <div class="contributors-list">
      <ul class="contributors" style="margin-left: 0; padding-left: 0;">
        <li v-for="item in contributors" :key="item.login">
          <a-tooltip :title="`${item.login}`">
            <a :href="item.url" target="_blank">
              <a-avatar :src="item.avatar" size="small" />
            </a>
          </a-tooltip>
        </li>
      </ul>
    </div>
  </div>
</template>

<style scoped>
.contributors-container {
  margin-top: 120px !important;
}

.title {
  font-size: var(--ant-font-size-sm);
  opacity: 0.5;
  margin-bottom: var(--ant-margin-xs);
}

.contributors-list {
  display: flex;
  gap: 8px;
}

.contributors-list span {
  color: var(--ant-color-primary);
}

.contributors {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-flex-wrap: wrap;
  -webkit-flex-wrap: wrap;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
  clear: both;
  flex: 1;
}

.contributors li {
  height: 24px;
}

.contributors li,
.contributors .ant-avatar + .ant-avatar {
  -webkit-transition: all 0.3s;
  transition: all 0.3s;
  -webkit-margin-end: -8px;
  margin-inline-end: -8px;
}

.contributors:hover li,
.contributors:hover .ant-avatar {
  -webkit-margin-end: 0;
  margin-inline-end: 0;
}

li {
  list-style: none;
}
</style>
