<script setup lang="ts">
import { computed } from 'vue'

// contributors.json is generated by `pnpm contributors` (scripts/generate-contributors.ts).
// The eager glob keeps the page safe when the file has not been generated yet.
const files = import.meta.glob('@/assets/contributors.json', { eager: true, query: '?raw', import: 'default' })

const logins = computed<string[]>(() => {
  const raw = Object.values(files)[0]
  if (!raw) {
    return []
  }
  try {
    const data = JSON.parse(String(raw))
    return Array.isArray(data?.logins) ? data.logins : []
  }
  catch {
    return []
  }
})
</script>

<template>
  <a-flex v-if="logins.length" wrap gap="small">
    <a-tooltip v-for="login in logins" :key="login" :title="login">
      <a :href="`https://github.com/${login}`" target="_blank" rel="noreferrer">
        <img
          class="contributor-list-avatar"
          :src="`https://github.com/${login}.png?size=80`"
          :alt="login"
          loading="lazy"
        >
      </a>
    </a-tooltip>
  </a-flex>
</template>

<style scoped>
.contributor-list-avatar {
  width: 36px;
  height: 36px;
  vertical-align: middle;
  border: 1px solid var(--ant-color-border-secondary);
  border-radius: 50%;
  transition: transform var(--ant-motion-duration-mid);
}

.contributor-list-avatar:hover {
  transform: translateY(-2px);
}
</style>
