import type { DefaultComponentDefinition } from './types'

export const defaultComponents: DefaultComponentDefinition[] = [
  {
    componentName: 'ProConfigProvider',
    tagName: 'ap-config-provider',
    description: 'Provides shared configuration for Pro components.',
    lang: 'both',
    attributes: [
      { name: 'prefixCls', description: 'Prefix class name for components.', type: 'string' },
      { name: 'iconPrefixCls', description: 'Prefix class name for icons.', type: 'string' },
      { name: 'direction', description: 'Text direction.', type: '\'ltr\' | \'rtl\'' },
      { name: 'theme', description: 'Theme configuration.', type: 'ThemeConfig' },
      { name: 'componentSize', description: 'Default size of components.', type: '\'small\' | \'middle\' | \'large\'' },
      { name: 'componentDisabled', description: 'Whether components are disabled by default.', type: 'boolean' },
      { name: 'getPopupContainer', description: 'Container for popup elements.', type: '(triggerNode?: HTMLElement) => HTMLElement' },
      { name: 'getTargetContainer', description: 'Container used for scrolling and fixed elements.', type: '() => HTMLElement | Window' },
      { name: 'csp', description: 'Content Security Policy configuration.', type: '{ nonce?: string }' },
      { name: 'renderEmpty', description: 'Render empty content for components.', type: '(...args: any[]) => any' },
      { name: 'virtual', description: 'Whether virtual scrolling is enabled.', type: 'boolean' },
      { name: 'popupMatchSelectWidth', description: 'Whether popup width matches the select width.', type: 'boolean' },
      { name: 'popupOverflow', description: 'Popup overflow strategy.', type: '\'viewport\' | \'scroll\'' },
      { name: 'scrollbar', description: 'Default Scrollbar configuration.', type: 'ScrollbarConfig' },
      { name: 'inputTag', description: 'Default InputTag configuration.', type: 'InputTagConfig' },
    ],
    slots: [
      { name: 'default', description: 'Content rendered inside the provider.' },
    ],
  },
  {
    componentName: 'InputTag',
    tagName: 'a-input-tag',
    description: 'Text tag input without dropdown or search behavior.',
    lang: 'both',
    attributes: [
      { name: 'value', description: 'Controlled tag values.', type: 'string[]' },
      { name: 'defaultValue', description: 'Initial tag values.', type: 'string[]' },
      { name: 'inputValue', description: 'Controlled editor text.', type: 'string' },
      { name: 'defaultInputValue', description: 'Initial editor text.', type: 'string' },
      { name: 'placeholder', description: 'Input placeholder.', type: 'string' },
      { name: 'disabled', description: 'Disable editing.', type: 'boolean' },
      { name: 'readonly', description: 'Make the editor read-only.', type: 'boolean' },
      { name: 'maxCount', description: 'Maximum number of tags.', type: 'number' },
      { name: 'tokenSeparators', description: 'Characters or strings that commit tags.', type: 'string[]' },
      { name: 'allowDuplicate', description: 'Allow duplicate tag values.', type: 'boolean' },
      { name: 'allowClear', description: 'Show a clear action.', type: 'boolean' },
      { name: 'classes', description: 'Semantic class names.', type: 'InputTagClassNamesType' },
      { name: 'styles', description: 'Semantic styles.', type: 'InputTagStylesType' },
    ],
    events: [
      { name: 'update:value', description: 'Emitted when tags change.', type: '(value: string[]) => void' },
      { name: 'change', description: 'Emitted after a tag list change.', type: '(value: string[], info: InputTagChangeInfo) => void' },
      { name: 'add', description: 'Emitted for each added tag.', type: '(value: string, info: { index: number }) => void' },
      { name: 'remove', description: 'Emitted for each removed tag.', type: '(value: string, info: { index: number }) => void' },
      { name: 'clear', description: 'Emitted when all values are cleared.', type: '(event: MouseEvent) => void' },
    ],
    slots: [
      { name: 'prefix', description: 'Content before tags.' },
      { name: 'suffix', description: 'Content after the editor.' },
      { name: 'clearIcon', description: 'Custom clear icon.' },
      { name: 'tag', description: 'Custom tag renderer.' },
    ],
  },
]
